### ISSUE TITLE
ERROR: onnxruntime-native-1.8.2-r0 do_fetch: Fetcher failure for URL: 'git://github.com/google/protobuf.git;branch=master;name=protobuf'. Unable to fetch URL from any source.

### ISSUE THREAD

**Issue by nixondutt** [Freescale/meta-freescale-ml#38]
While trying to build onnxruntime receipe on hardknott branch, I am coming accross the following error. 

I tried with changing the branch from master to main, as there is no master branch in protobuf git repository. Even though bitbake can fetch and compile, it is unable to install onnxruntime. 

The command I used in local.conf file is IMAGE_INSTALL_append += " onnxruntime"

WARNING: onnxruntime-native-1.8.2-r0 do_fetch: Failed to fetch URL git://github.com/google/protobuf.git;branch=master;name=protobuf, attempting MIRRORS if available
ERROR: onnxruntime-native-1.8.2-r0 do_fetch: Fetcher failure: Unable to find revision 2dc747c574b68a808ea4699d26942c8132fe2b09 in branch master even from upstream
ERROR: onnxruntime-native-1.8.2-r0 do_fetch: Fetcher failure for URL: 'git://github.com/google/protobuf.git;branch=master;name=protobuf'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/nixon/var-fsl-yocto/build_xwayland/tmp/work/x86_64-linux/onnxruntime-native/1.8.2-r0/temp/log.do_fetch.242868
ERROR: Task (/home/nixon/var-fsl-yocto/sources/meta-freescale-ml/recipes-libraries/onnxruntime/onnxruntime-native_1.8.2.bb:do_fetch) failed with exit code '1'

**Comment by otavio** [comment]
Please check if this happens in kirkstone.

**Comment by otavio** [comment]
@chrisdimich could you take a look at this?

**Comment by chrisdimich** [comment]
Fixed by #45
